baseURL: "https://angel-721.github.io/"
languageCode: "en-us"
title: "Angel Velasquez"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Angel Velasquez"
  description: A personal portfolio site for Angel Velasquez
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: false

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "AV" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Angel Velasquez."
    # subtitle: "I build things for the web"
    content: "Aspiring data scientist with a strong interest in human computer interaction."
    image: https://media.licdn.com/dms/image/D5603AQGoafS7VmoVng/profile-displayphoto-shrink_800_800/0/1696295200250?e=1701907200&v=beta&t=cpqvHh5o2WjLDYwzRcVk-oDE_0guZ1Gd61eddcQO48Q
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/angel-721
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/angel-velasquez-569102184/
        # - icon: fab fa-twitter
        #   url: https://example.com
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    # image: "/images/me.png"
    content: |-
      I currently intern as a VR software engineer for [Utah Tech Online](https://online.utahtech.edu/immersive/). I'm a senior Software Engineering major at Utah Tech University with a emphasis in Data Science and AI.

#      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "C# (Unity)"
        - "C++"
        - "HTML/CSS"
        - "JavaScript"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "VR Software Engineer Intern | Intern"
        company: "Utah Tech Online"
        companyUrl: "https://online.utahtech.edu/immersive/"
        date: "May 2022 - present"
        featuredLink:
          enable: false
          name: ""
          url: ""
        content: "I'm part of a team that develops VR learning experiences for Utah Tech Online Students. The most recent project that I'm helping with is a physics lab course made in Unity."


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Software Engineering | B.S."
        school:
          name: "Utah Tech University"
          url: "https://cd.utahtech.edu/"
        date: "2022 - 2024"
        GPA: "3.9 out of 4.0"
        content: |-
          - Coursework in Machine Learning, Artificial Intelligence, and Data Visualization.
          - Graduated with A.S in general studies with high honors.

          ##### Extracurricular Activities
            - Founding member of the Utah Tech University Game Makers Club. A club dedicated to the cause of uniting students interested in game development.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Non-Resident University Scholar
        content: Second highest scholarship awarded to non-resident students at Utah Tech University.
        # url: https://example.com
        # image: /images/achievment.jpg
      - title: Utah Tech Department of Computing Programming Competition(2023)
        content: Second place in the advanced division of the Utah Tech Department of Computing Programming Competition.
        image: "/images/contest.jpg"
      # - title: Hugo Profile
      #   content: Developed a theme and getting 1K+ downloads per month.
      #   url: "https://github.com/gurusabarish/hugo-profile"
      #   image: /images/achievment.jpg
      - title: ASPIRE-Utah Scholar
        content: Awarded to Utah TRIO students who have shown academic excellence. TRIO is a program to help first generation, income-eligible, and students with disabilities succeed in higher education.
      # - title: Google Summer of Code
      #   content: Contributed to a open source project.
      #   url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Ultimate Fight Predictor(UFP)
        content: A model built to predict the outcome of UFC fights using the Sklearn library in Python.
        image: https://user-images.githubusercontent.com/75283919/244850274-9a668142-38ec-4af5-842f-177e09962033.png
        # featured:
          # name: Demo
          # link: https://hugo-profile.netlify.app
        badges:
          - "Python"
          - "Sklearn"
          # - "Javascript"
        links:
          # - icon: fa fa-envelope
            # url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/angel-721/UFP
          # - icon: fab fa-twitter
            # url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Tweepy Media Bot
        content: A Python skeleton frame work for Twitter bots that can tweet images and videos.
        image:  https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/twitter-icon.png
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Python"
          - "SQLite"
          - "Tweepy"
          - "AWS"
        links:
          - icon: fab fa-github
            url: https://github.com/angel-721/tweepy-media-bot

      - title: Tapology Python Parser
        content: A python scraper that parses data from the Tapology website for use in data science projects.
        # image: /images/projects/profile2.jpg
        image: https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/files/python-logo-only.svg
        featured:
          # name: Demo V2
          # link: https://hugo-profile-2.netlify.app
        badges:
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/angel-721/tapology-python-parser

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: 
    email: angelvelasquez2002@gmail.com
    btnName: Email Me!
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://angel-721.github.io/
      linkedin: https://linkedin.com/in/angel-velasquez-569102184/
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

    # title: "Custom Name"

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: true

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
